version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/ci-cd-deploy/FlaskAppCodeDeploy
   overwrite: true
file_exists_behavior: OVERWRITE
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300
     runas: root